spring:
  datasource:
    url: jdbc:h2:mem:sbdb
    username: sarfraz
    password: sarfraz@123
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  
    
server:
  port: 9091    